repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # Updated by autoupdate
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

#  - repo: https://github.com/trufflesecurity/trufflehog
#    rev: v3.88.30 # Updated to latest and corrected hook
#    hooks:
#      - id: trufflehog # Corrected ID, removed other fields now covered by hook definition

  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.9.0 # Updated by autoupdate
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt"]
